services:
  samba_authentik:
    build: .
    container_name: samba_authentik
    restart: always

    cap_add:
      - CAP_NET_ADMIN

    ports:
      - "137:137/udp"
      - "139:139" 
      - "446:445"

    networks:
      integrated:
        interface_name: int0
        
        ipv4_address: 192.168.2.9
        ipv6_address: 'fd2a:89e6:4e8f::daad:f17e'
        mac_address: '22:E6:48:9D:CC:77'

networks:
  integrated:
    external: true
