services:
  samba_authentik:
    build: 
      context: .
      no_cache_filter: configure
    container_name: samba_authentik
    restart: no

    volumes:
      - samba:/var/lib/samba/:rw
      - logdb:/var/log:rw
      - pblic:/myshares/public:rw
      - homes:/homes:rw
      - dms:/myshares/paperless:rw
    cap_add:
      - CAP_NET_ADMIN

    ports:
      - "137:137/udp"
      - "139:139" 
      - "446:445"

    environment:
      - LDAP_AK_URI=${LDAP_AK_URI:-ldap://host.docker.internal:3489}
      - LDAP_BASE_DN=${LDAP_BASE_DN:-testpw}
      - LDAP_ADMIN_DN_USERCN=${LDAP_ADMIN_DN_USERCN:-testpw}
      - LDAP_ADMIN_DN_PASSWORD=${LDAP_ADMIN_DN_PASSWORD:-testpw}
#     networks:
#       integrated:
#         #interface_name: int0

#         ipv4_address: 192.168.2.9
#         ipv6_address: 'fd2a:89e6:4e8f::daad:f17e'
#         mac_address: '22:E6:48:9D:CC:77'

# networks:
#   integrated:
#     external: true

volumes:
  samba:
  logdb:
  dms:
  homes:
  pblic: