name: sambafileserverldap

services:
  smbFileserverLdap:
    image: smb.fileserver.ldap
    container_name: SambaFileserverLdap

    build: 
      context: .
      no_cache_filter: configure
      #provenance: mode=max
      #sbom: true
      tags:
        - git.homelab.kellner-digital.com/mario/smb.fileserver.ldap:latest # homelab gitea repo
        - smb.fileserver.ldap:latest

    restart: no
    
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

    cap_add:
      - CAP_NET_ADMIN
    
    # network_mode: host

    ports:
      - 137:137/udp
      - 139:139/tcp
      - 445:445/tcp
      #- 446:445
      - 3702:3702/udp
      - 3702:3702/tcp
      - 5354:5353/udp
      - 5354:5353/tcp
      - 5355:5355/udp
      - 5355:3555/tcp

    environment:
      LDAP_AK_URI: ${LDAP_AK_URI}
      LDAP_BASE_DN: ${LDAP_BASE_DN}
      LDAP_ADMIN_DN_USERCN: ${LDAP_ADMIN_DN_USERCN}
      LDAP_ADMIN_DN_PASSWORD: ${LDAP_ADMIN_DN_PASSWORD}
