[global]
  security = user
  server role = standalone server

  #server min protocol = SMB2
  #server max protocol = SMB3
  idmap cache time = 7200

  socket options = IPTOS_LOWDELAY TCP_NODELAY IPTOS_THROUGHPUT
  use sendfile = yes

  load printers = No
  printcap name = /dev/null
  disable spoolss = yes

  strict locking = no
  oplocks = yes
  level2 oplocks = yes
  kernel oplocks = yes

  vfs objects = catia fruit streams_xattr
  fruit:resource = file
  fruit:metadata = stream
  fruit:locking = netatalk
  fruit:encoding = native
  fruit:model = TimeCapsule
  fruit:aapl = yes

  mangled names = no
  dos charset = CP850
  unix charset = UTF-8

  # LDAP
  obey pam restrictions = yes 
  pam password change = no
  ldap passwd sync = Off
  ldap timeout = 2
  ldap connection timeout = 2

  # Further LDAP defaults will be written by script
  # passdb backend, ldap admin dn, ldap suffix, ldap group suffix