name: Build and push container image
run-name: ${{ github.actor }} is building and pushing container image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write


    env:
      REGISTRY:  ${{ vars.PRIVATE_REGISTRY }}
      IMAGE_NAME: smb.fileserver.ldap
      NS: public
      IMG_PATH_GITEA: ${{ env.REGISTRY }}/${{ env.NS }}/${{ env.IMAGE_NAME }}
      CACHE_IMAGE: ${{ vars.PRIVATE_REGISTRY }}/public/smb.fileserver.ldap:buildcache


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: | 
            ${{ env.IMG_PATH_GITEA }}
          
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix=sha-
            type=raw,value=${{ github.sha }}
          labels: |
            org.opencontainers.image.authors="Mario Kellner"
            org.opencontainers.image.licenses="MIT"
            org.opencontainers.image.title="SMB Fileserver with LDAP Integration"
            org.opencontainers.image.title="SMB Fileserver with Integration for LDAP Providers. Mainly designed for use with Authentik, but should work with any LDAP provider that supports the used schema."
            org.opencontainers.image.url="https://www.kellner-digital.com"
            org.opencontainers.image.base.name="debian:trixie-slim"

      - name: Login to Gitea Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        id: push
        with:
          context: .
          file: ./Dockerfile
          push: true
          sbom: true
          provenance: mode=max
          platforms: linux/amd64,linux/arm64

          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

          cache-from: |
            type=registry,ref=${{ env.CACHE_IMAGE }}

          cache-to: |
            type=registry,ref=${{ env.CACHE_IMAGE }},mode=max

          build-args: |
                  BUILDKIT_INLINE_CACHE=1