[sssd]
services = nss, pam
config_file_version = 2
domains = kelfam.de

[domain/kelfam.de]
id_provider = ldap
auth_provider = ldap

ldap_uri = ldap://192.168.2.191:389
ldap_search_base = dc=kelfam,dc=de

ldap_default_bind_dn = cn=ldapservice,dc=kelfam,dc=de
ldap_default_authtok = testpw

cache_credentials = true

enumerate = true

ldap_user_uid_number = uidNumber
ldap_user_gid_number = gidNumber
ldap_user_home_directory = homeDirectory