uid nslcd
gid nslcd

uri ldap://host.docker.internal:3489
tls_reqcert never

base dc=kelfam,dc=de
binddn cn=ldapservice,dc=kelfam,dc=de
bindpw testpw

base passwd ou=users,dc=kelfam,dc=de
base group ou=groups,dc=kelfam,dc=de

filter passwd (&(objectClass=user)(memberOf=cn=smbshr,ou=groups,dc=kelfam,dc=de))
filter group (objectClass=group)

map    passwd uid cn
map    passwd uidNumber        uidNumber
map    passwd gidNumber        gidNumber
map    passwd homeDirectory    homeDirectory
map    passwd loginShell       loginShell

log /var/log/nslcd.log INFO
