uid nslcd
gid nslcd

map    passwd uid cn
map    passwd uidNumber        uidNumber
map    passwd gidNumber        gidNumber
map    passwd homeDirectory    homeDirectory
map    passwd loginShell       loginShell
