uid nslcd
gid nslcd

uri ldap://localhost
tls_reqcert never

base dc=example,dc=org
binddn cn=user,dc=kelfam,dc=de
bindpw testpw

base passwd ou=users,dc=example,dc=org
base group ou=groups,dc=example,dc=org

filter passwd (&(objectClass=user)(memberOf=cn=smbshr,ou=groups,dc=kelfam,dc=de))
filter group (objectClass=group)

map    passwd uid cn
map    passwd uidNumber        uidNumber
map    passwd gidNumber        gidNumber
map    passwd homeDirectory    homeDirectory
map    passwd loginShell       loginShell

log /var/log/nslcd.log INFO
