[supervisord]
nodaemon=true
user=root

[program:nmbd]
command=nmbd -i
autostart=true
autorestart=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:avahi]
command=avahi-daemon --no-drop-root --debug --no-rlimits
autostart=true
autorestart=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:nslcd]
command=nslcd -d
autostart=true
autorestart=true
user=root

stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:wsdd2]
command=wsdd2
autostart=true
autorestart=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:samba]
command=bash -c 'sleep 5 && smbd -i --foreground --debug-stdout -d 3'
autostart=true
autorestart=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

# [group:samba-services]
# programs=nmbd,wsdd2,nslcd,avahi,samba