[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0

[eventlistener:processes]
command=bash -c "while read line; do kill -SIGQUIT $PPID; done < /dev/stdin"
events=PROCESS_STATE_FATAL,PROCESS_STATE_BACKOFF,PROCESS_STATE_EXITED

[program:nmbd]
command=nmbd -i
autostart=true
autorestart=true
user=root
priority=1
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:avahi]
command=avahi-daemon --no-drop-root --no-rlimits
autostart=true
autorestart=true
user=root
priority=1
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:nslcd]
command=nslcd -n
autostart=true
autorestart=true
user=root
priority=1
stdout_logfile_maxbytes=0
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:wsdd2]
command=wsdd2
autostart=true
autorestart=true
user=root
priority=1
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:samba]
command=smbd --foreground --no-process-group
autostart=true
autorestart=true
user=root
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=2 
numprocs=1
startsecs=10