[global]
        additional dns hostnames = samba2 fileserver2 file-srv2
        bind interfaces only = Yes
        guest account = smbusr
        interfaces = int0
        load printers = No
        log file = /dev/stdout
        map to guest = Bad User
        mdns name = mdns
        netbios aliases = samba fileserver file-srv
        ntlm auth = ntlmv1-permitted
        obey pam restrictions = yes
        pam password change = yes
        passdb backend = tdbsam
        printcap name = /dev/null
        security = USER
        server role = standalone server
        server string = Netzwerk Speicher der Familie Kellner (Samba)
        smb1 unix extensions = No
        socket options = IPTOS_LOWDELAY TCP_NODELAY IPTOS_THROUGHPUT
        usershare allow guests = Yes
        fruit:aapl = yes
        fruit:model = TimeCapsule
        fruit:encoding = native
        fruit:locking = netatalk
        fruit:metadata = stream
        fruit:resource = file
        idmap config * : backend = tdb
        acl allow execute always = Yes
        guest ok = Yes
        mangled names = no
        vfs objects = catia fruit streams_xattr
        wide links = Yes


[DMS Ablage]
        comment = DMS Ablage (Cosume new Files here)
        create mask = 0666
        directory mask = 0775
        force create mode = 0666
        force directory mode = 0775
        force group = smbshr
        force user = smbusr
        path = /myshares/paperless
        read only = No


[Privat %U]
        comment = Persönlicher Freigabe Ordner für valide Benutzer
        force group = smbshr
        guest ok = No
        path = /myshares/homes/%U
        read only = No
        root preexec = /container/scripts/samba_create_user_dir.sh /myshares/homes %U


[Daten]
        comment = Austausch & Transfer für alle Nutzer
        create mask = 0664
        directory mask = 0775
        force create mode = 0664
        force directory mode = 0775
        force group = smbshr
        path = /myshares/public
        read only = No