[global]
        additional dns hostnames = samba2 fileserver2 file-srv2
        #bind interfaces only = Yes
        #interfaces = int0
        min protocol = SMB2

        add user script = /usr/local/samba/bin/add_user %u

        guest account = smbusr
        map to guest = Bad User

        load printers = No
        printcap name = /dev/null

        log file = /var/log/samba/%m
        log level = 3

        mdns name = mdns
        netbios name = sambaAuthentik
        # ntlm auth = yes

        obey pam restrictions = yes 
        pam password change = no

        passdb backend = tdbsam
        ldap admin dn = cn=ldapservice,ou=users,dc=example,dc=org
        ldap suffix = dc=example,dc=org
        ldap user suffix = ou=users
        ldap group suffix = ou=groups
        ldap passwd sync = Off
        ldap ssl = Off

        security = USER
        server role = standalone server
        server string = Netzwerk Speicher der Familie Kellner
        workgroup = WORKGROUP
        disable netbios = yes
        smb1 unix extensions = No

        socket options = IPTOS_LOWDELAY TCP_NODELAY IPTOS_THROUGHPUT

        usershare allow guests = Yes

        ea support = yes

        # MacOS Compatibility options
        # for now without xattr, i dont even have a mac
        vfs objects = catia fruit  streams_xattr
	fruit:resource = file
	fruit:metadata = stream
	fruit:locking = netatalk
	fruit:encoding = native

        # Special configuration for Apple's Time Machine
        fruit:model = TimeCapsule
        fruit:aapl = yes

        acl allow execute always = Yes

        guest ok = Yes

        mangled names = no
        dos charset = CP850
        unix charset = UTF-8
        
        printcap name = /dev/null
        load printers = no
        
        dns proxy = no
        
        follow symlinks = yes
        unix extensions = no
        acl allow execute always = yes

[DMS Ablage]
        comment = DMS Ablage (Cosume new Files here)
        create mask = 0666
        directory mask = 0775
        force create mode = 0666
        force directory mode = 0775
        force group = smbshr
        force user = smbusr
        path = /myshares/paperless
        read only = No


[Privat %U]
        comment = Persönlicher Freigabe Ordner für valide Benutzer
        guest ok = No
        path = /homes/%U
        read only = No

        root preexec = /makeHome.sh /homes %U

[Daten]
        comment = Austausch & Transfer für alle Nutzer
        create mask = 0664
        directory mask = 0775
        force create mode = 0664
        force directory mode = 0775
        
        force group = smbshr
        force user = smbusr
        
        path = /myshares/public
        read only = No
